node {
    def commit_id
    stage('Prep') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"
        commit_id = readFile('.git/commit-id').trim()
    }
    stage('Build') {
        sh "mvn archetype:generate -DgroupId=sapient.tutorial.maven -DartifactId=maven-tutorial-example -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false
    }
}
